ARG DKRENV_IMG
FROM ${DKRENV_IMG}:devel as watcher
COPY ./approot/deps/ /usr/src/app/deps/
COPY ./approot/dist/ /usr/src/app/dist/


FROM ${DKRENV_IMG}:latest
COPY --from=watcher /usr/src/app/deps/ /usr/src/app/deps/
COPY --from=watcher /usr/src/app/dist/ /usr/src/app/dist/

# vim: ft=dockerfile
